# Generated by Django 3.0.8 on 2020-07-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('album_title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('album_art', models.ImageField(default='', upload_to='album')),
                ('slug', models.CharField(max_length=150)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('author', models.TextField()),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('image', models.ImageField(default='', upload_to='poem')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=300)),
                ('mp3', models.FileField(default='', upload_to='album')),
                ('thumbnail', models.ImageField(default='', upload_to='album')),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimerwebsite.Album')),
            ],
        ),
    ]
