# Generated by Django 3.0.8 on 2020-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimerwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='poem',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='mp3',
            field=models.FileField(default='', upload_to='album/mp3'),
        ),
        migrations.AlterField(
            model_name='song',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
